name: my_cv_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.1
  flutter_rating_stars: ^1.0.3+4
  font_awesome_flutter: ^10.5.0
  styled_text: ^8.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/main_page/
    - assets/images/languages/
    - assets/images/projects/
    - assets/images/flags/
    - assets/images/courses/
    - assets/images/logos/
    - assets/pdf/cv.pdf
    - assets/images/main_page/computer.jpg
    - assets/images/main_page/phone.jpg
    - assets/images/main_page/study.jpg
    - assets/images/main_page/light_buble.jpg
    - assets/images/main_page/world.jpg

    
